# Generated by Django 5.2.1 on 2025-06-12 17:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("completions", "0001_initial"),
        (
            "habits",
            "0004_habit_completed_habit_last_completed_at_habit_streak_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="completion",
            name="habit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="completion_entries",
                to="habits.habit",
            ),
        ),
        migrations.AlterField(
            model_name="completion",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="completion_records",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
