# Generated by Django 5.2.1 on 2025-05-29 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="habit",
            name="xp",
            field=models.PositiveIntegerField(default=10),
        ),
    ]
