# Generated by Django 5.2.1 on 2025-06-12 17:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0003_completion"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="habit",
            name="completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="habit",
            name="last_completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="habit",
            name="streak",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name="HabitCompletion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("streak", models.PositiveIntegerField(default=0)),
                (
                    "habit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="habit_completions",
                        to="habits.habit",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="habit_completion_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("habit", "user", "completed_at")},
            },
        ),
        migrations.AddField(
            model_name="habit",
            name="completions",
            field=models.ManyToManyField(
                blank=True,
                related_name="habits_completed",
                through="habits.HabitCompletion",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.DeleteModel(
            name="Completion",
        ),
    ]
